version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: postgres-db
    environment:
      POSTGRES_DB: test_project
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Bana54321bana3024
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  app:
    build: .
    container_name: spring-boot-app
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/test_project
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: Bana54321bana3024
      SPRING_JPA_HIBERNATE_DDL_AUTO: none
      SPRING_LIQUIBASE_CHANGELOG: classpath:/db/changelog/db.changelog-master.yaml
    ports:
      - "8080:8080"
    depends_on:
      - postgres

volumes:
  postgres-data: